### ISSUE TITLE
Error No SeuratObject

### ISSUE THREAD

**Issue by mthimma** [crazyhottommy/scclusteval#10]
Hi I am running the snakemake workflow on my seurat object (after renaming it to seurat_obj.rds)
But facing the following issue.
>more 00log/full_sample_k_8_resolution_1.4_PC_150.log
Loading required package: SeuratObject
Error in .requirePackage(package) : 
  unable to find required package ‘SeuratObject’
Calls: eval ... .extendsForS3 -> extends -> getClassDef -> .requirePackage
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘SeuratObject’
Execution halted

**Comment by crazyhottommy** [comment]
can you please try the new release of the snakemake workflow and install SeuratObject package too?
