### ISSUE TITLE
Subsetting data on combined Seurat with Harmony embeddings

### ISSUE THREAD

**Issue by Jay-Leung** [crazyhottommy/scclusteval#12]
Hello,

I am currently looking at evalutating cluster stability of a Seurat object consisting of 4 datasets with SCTransform and Harmony embeddings for batch effect correction. I understand that the function PreprocessSubsetData runs FindVariableGenes, ScaleData, RunPCA, JackStraw...in this case, will this package work, since JackStraw is not compatible with SCTransform, and if I specify the number of PCs, can it access the harmony embeddings to FindClusters?

Thanks!

**Comment by crazyhottommy** [comment]
Hi, you should https://github.com/crazyhottommy/pyflow_seurat_parameter for subsetting and reclustering.  now it is using SCTransform https://github.com/crazyhottommy/pyflow_seurat_parameter/blob/master/scripts/preprocess.R#L44
if you want to use harmony PC, you will need to change this https://github.com/crazyhottommy/pyflow_seurat_parameter/blob/master/scripts/preprocess.R#L52 to RunHarmony and other downstream to use harmony pc for findcluters.

**Comment by Paria06** [comment]
Hi @crazyhottommy 
I would like to make sure I made the changes correctly as I'm doing SCT and Harmony. The changes Made are as below:
L52 (RunPCA > RunHarmony): 
set.seed(1)
object<- RunHarmony(object = object, assay.use="SCT", group.by.vars = "orig.ident")

L76-77 (pca > harmony): 
object<- FindNeighbors(object, dims = 1:pc.use, k.param = k.param, nn.eps = nn.eps,
                               verbose = FALSE, reduction = "harmony", force.recalc = TRUE)

Moreover, does it matter How I do the steps and what I regress out? below is my code for SCT and harmony:
code: 
![image](https://user-images.githubusercontent.com/52675953/181156105-31eef9d9-d0ea-4132-bf37-73f4e808cefd.png)

Thank you in advance!
