### ISSUE TITLE
UMAP parameter to get reasonable clusters layout

### ISSUE THREAD

**Issue by MarcusLCC** [crazyhottommy/scclusteval#15]
Hi Ming,

Thanks for developing this tool and also for your lectures on youtube :)

I've made several runs successfully. After getting the results, I plotted the rainplot and selected the best parameters that produce high and stable scores for the clusters.

However, when I then want to visualise the clusters through UMAP with default parameters and the number of PCA (30 here) I used with scclusteval, e.g. `RunUMAP(seurat_integrated_SCT, reduction = "pca", dims = 1:30)`, the clusters layout seems a bit strange. Many clusters to some extent overlap with the adjacent clusters and doesn't seem to be very clean, and some clusters are even split into two by another cluster.

I'm guessing it may have something to do with the UMAP parameter, which I usually just use the default and don't know how to fine-tune in this case.

May I know if you have some suggestions on this case? Sorry because it seems not related to the package itself. I would appreciate a lot if you have some advice.

Best,
Marcus

**Comment by crazyhottommy** [comment]
Hi Marcus, can you please post some UMAP and make sure I understand what are you talking about? thanks

**Comment by MarcusLCC** [comment]
Hi Ming,

No problem.

This is the UMAP that I get using the cluster produced by the selected parameters.
Specifically, I use 50 PCA to run scclusterval. After evaluating the results, I selected res=0.5, k=80 for clustering.
I loaded the seurat object with corresponding parameters in the "full_sample" directory, and then:
```
RunUMAP(seurat_integrated_SCT, reduction = "pca", dims = 1:50)
pdf("UMAP.integrated.scclusteval_para.pdf", width=9, height=7)
DimPlot(seurat_integrated_SCT, reduction = "umap", label = TRUE, label.box = FALSE, label.size = 3.5, raster=FALSE, group.by="seurat_clusters",
        cols = c(pal_npg("nrc", alpha = 0.9)(10), pal_simpsons("springfield")(14), pal_nejm(palette = c("default"), alpha = 1)(8)))
dev.off()
```


[UMAP.integrated.scclusteval_para.pdf](https://github.com/crazyhottommy/scclusteval/files/7879157/UMAP.integrated.scclusteval_para.pdf)

![image](https://user-images.githubusercontent.com/61820820/149711999-b7c46a06-432e-4589-99e8-8c544ba2cf64.png)


As can be seen, many cells annotated as cluster 11 extend to cluster 3, and on the right side of cluster 10 you can find light blue dots which are cells belonging to cluster 11, and between cluster 6 and 4 there're some grey dots from cluster 12.

I remember when I uses the default k_param for clustering this situation won't happen, so I'm guessing the change of k_param leads to this issue, while my UMAP step didn't make adjustment to reflect that change.

May I know your opinions on whether or how I should adjust the UMAP parameter for better presentation?

Many thanks,

Best
Marcus

**Comment by crazyhottommy** [comment]
UMAP is just a visualization tool for the clusters identified by the community detection algorithm.  The distance between the points does not mean much (as opposed to distances between points in PCA. I also have some clusters overlap with each other on UMAP in my own data. Can you post the other UMAP that you think is better?

**Comment by MarcusLCC** [comment]
Thank you Ming for educating. I see.

![image](https://user-images.githubusercontent.com/61820820/149867964-d2bbde3d-7da9-42cb-84dc-28bc200f2f61.png)

I checked the UMAPs produced before and I did also find some overlapping like this. Maybe it's acceptable? I might have some misunderstanding on the UMAP and I'll read more on it.

Thanks again,

Best
Marcus

**Comment by crazyhottommy** [comment]
I think it looks fine.
