### ISSUE TITLE
How do I use SCTransform+harmony integrated dataset for scclusteval cluster evaluation

### ISSUE THREAD

**Issue by Paria06** [crazyhottommy/scclusteval#16]
Hi @crazyhottommy
I would like to make sure I made the changes correctly as I'm doing SCT and Harmony. The changes Made are as below:
L52 (RunPCA > RunHarmony):
set.seed(1)
object<- RunHarmony(object = object, assay.use="SCT", group.by.vars = "orig.ident")

L76-77 (pca > harmony):
object<- FindNeighbors(object, dims = 1:pc.use, k.param = k.param, nn.eps = nn.eps,
verbose = FALSE, reduction = "harmony", force.recalc = TRUE)

Moreover, does it matter How I do the steps and what I regress out? below is my code for SCT and harmony:
code:
![image](https://user-images.githubusercontent.com/52675953/182411860-2a48eaff-806f-40e3-8fbe-1395e519a533.png)

I have one more question; do I need to edit the preprocess.R script as it specified the pc.use=20 and in the downstream analysis it stops if the code asks for more than 20 PCs.

Thank you in advance!

**Comment by crazyhottommy** [comment]
The code looks okay to me.

and yes, for pc.use https://github.com/crazyhottommy/pyflow_seurat_parameter/blob/master/scripts/preprocess.R#L29
