### ISSUE TITLE
Should I do ScaleData on my integrated data as an input for scclusteval

### ISSUE THREAD

**Issue by Paria06** [crazyhottommy/scclusteval#17]
Dear @crazyhottommy 
In the preprocess.R script should I add ScaleData before RunPCA as I haven't run it on my integrated data. Or I need to  run it on my integrated data?
Thanks,
Paria

**Comment by crazyhottommy** [comment]
SCTransform replaces NormalizeData, ScaleData and FindVariableFeatures.
what normalization did you use?

**Comment by Paria06** [comment]
Thanks for your response. I did NormalizeData, ScaleData before integration. So, there is no need to do it in preprocess.R right?what about adding ScaleData in subsample.R considering that I didn't do SCTransform. It is how I changed the subsample.R
meta.data.colnames <- object@meta.data %>% colnames()
    vars.to.regress <- c("percent.mt", "nCount_RNA")
    vars.to.regress <- vars.to.regress[vars.to.regress %in% meta.data.colnames]
    object <- ScaleData(object, vars.to.regress = vars.to.regress, model.use = "poisson", use.umi = TRUE)
    object <- RunPCA(object = object, features = VariableFeatures(object = object),
        npcs = num.pc)
    pc.use.meta <- rep(pc.use, length(colnames(object)))
    names(pc.use.meta) <- colnames(object)
    object <- AddMetaData(object = object, metadata = pc.use.meta,
        col.name = "pc.use")
    object <- RunHarmony(object, reduction.save = "harmony", 
                        group.by.vars = c("batchlib", "individual"))
    object <- UpdateSeuratObject(object)
    object <- FindNeighbors(object, reduction = "harmony", dims = 1:pc.use, k.param = k.param,
        nn.eps = nn.eps, verbose = FALSE, force.recalc = TRUE)
    object <- FindClusters(object = object, n.start = n.start,
        resolution = resolution, verbose = FALSE, algorithm = 2)
    return(object)
}

**Comment by crazyhottommy** [comment]
It does not hurt if you do ScaleData again.
