### ISSUE TITLE
no optimum combination of parameter

### ISSUE THREAD

**Issue by Paria06** [crazyhottommy/scclusteval#18]
Hey @crazyhottommy,
I did used scclusteval to evaluate cluster stability of my single cell dataset and I could easily get the optimum combination when I did Seurat integration. However, when I tried harmony it didn't happen and whatever I tried the number of total clusters are either very small or more than stable clusters. It is the same when I used Seurat integration (different filtering) again and I cannot get the optimum situation. I was wondering do you have idea why it's happening? could it mean that the change that I made result in unstable clusters ?  at some combination it returns like 10 total clusters and 5 stable clusters with 70,000 cells. I am not sure what could go wrong in my case.
I really appreciate any advice on this!
Paria

**Comment by crazyhottommy** [comment]
sorry, I did not see this message.

What dataset do you have? how many cell types do you expect? biology matters too

**Comment by Paria06** [comment]
It's okay. Based on my reference dataset I expect roughly 40 subclusters. I prefer to use harmony but it doesn't show a stable clustering. 
I also have a general question. When I use this tool I don't end up having all the subpopulations. Resulted clusters do cover the number of major cell types I expect. However, for some cell types all the subpopulations are clustered, for some it is only major cell type, and for some others for example if I expect 5 subpopulations I do have 3 and I am confused what to do in different classes. If I try to do sub clustering for some major cell types using scclusteval it doesn't support the higher resolution to get more clusters. What is your recommendation?
Thanks,
Paria

**Comment by crazyhottommy** [comment]
again, clustering is math. the clusters found by the mathematical method may not be biologically meaningful. There is no ground truth here. You said you expect 5, but how do you know it is 5? Also, I am testing https://github.com/igrabski/sc-SHC which is just out in Nature methods, but It seems to ignore biologically meaningful clusters too.
