### ISSUE TITLE
What if I want to get more cluster for a specific cluster resulted in using scclusteval

### ISSUE THREAD

**Issue by Paria06** [crazyhottommy/scclusteval#19]
Hi @crazyhottommy,
I did use scclusteval and the clustering resulted in 20 clusters. Now, I am considering to subset one of the cluster and do reclustering to get more clusters. Once I did this and used scclusteval again but the optimum parameter gave me one cluster. So, I am not sure what should I do in this case? does that mean if I increase the resolution the resulting clusters are not stable? and is there any way to overcome this issue?
Many thanks,
Paria

**Comment by crazyhottommy** [comment]
yeah, that means if you further cluster it the clusters become unstable.  Remember, one can always increase the resolution and get more clusters, but whether they are biologically meaningful or not is a question.

**Comment by Paria06** [comment]
I see. But my point is that if the number of cell types I expect is more than resulting clusters how I can have more stable clusters (which are biologically meaningful)?
Or I just need to subset and increase the resolution?
Thank you

**Comment by crazyhottommy** [comment]
yes, you will need to subcluster further
