### ISSUE TITLE
Installation error on Mac OS catalina (10.15.2)

### ISSUE THREAD

**Issue by Eomesodermin** [crazyhottommy/scclusteval#4]
I am struggling to get the package to install with 
> devtools::install_github("crazyhottommy/scclusteval")

I get the following error message

* installing *source* package ‘scclusteval’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
sh: line 1: 94961 Killed: 9               R_TESTS= '/Library/Frameworks/R.framework/Resources/bin/R' --no-save --slave 2>&1 < '/var/folders/bc/npspjlyx025bzz77sn2qb38c0000gn/T//RtmpvbZ7nZ/file172e8513747c4'
ERROR: lazy loading failed for package ‘scclusteval’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/scclusteval’
Error: Failed to install 'scclusteval' from GitHub:
  (converted from warning) installation of package ‘/var/folders/bc/npspjlyx025bzz77sn2qb38c0000gn/T//Rtmp05djPA/file16a3858a5bef4/scclusteval_0.0.0.9000.tar.gz’ had non-zero exit status
 
any suggestions?

**Comment by crazyhottommy** [comment]
Hi,
The error message is not so informative. Can you install it on a different machine?
I will need to set up GitHub action/Travis to test the installation on different platforms. 
I tried R3.6 and it worked on my recent installation, I will investigate and let you know.

Best,
Tommy

**Comment by Eomesodermin** [comment]
Hi, 

Thanks for the prompt reply. I tried on a different machine and installed after I updated Seurat to the dev version. 

Must be something specific to my machine. 

Thanks for the advice. :)
