### ISSUE TITLE
How to find stable subclusters?

### ISSUE THREAD

**Issue by Cumol** [crazyhottommy/scclusteval#5]
I was able to successfully use your workflow and found a good combination of PCs, K-parameters, and resolution where all found clusters are stable, so thank you first for this solution to this problem :)

Now trying to take it a step further. At higher values of K/resolution the number of total clusters increases and also the unstable clusters. However, there are also additional, smaller, stable clusters showing up. 

I was wondering if there is a way to do this on a sub-clustering basis.

Lets say you chose a specific combination of PCs, K, and resolution where all clusters are stable. And then in the next step, you subset the object into the found clusters and perform additional steps of clustering (to look for stable subclusters).

Have you thought about this? Do you think it is feasible with the current capabilities of the package?

**Comment by crazyhottommy** [comment]
great to hear it is working for you! 
After you find a good combination of k, PCs and resolution. 
you can then subset the Seurat object for the particular cluster for subclustering. Then you can use this subsetted smaller Seurat object and go through the snakemake workflow again to find stable small subclusters?

**Comment by Cumol** [comment]
This is what I am trying right now, using a fixed PC and k but different resolutions. I will report once I know more.

**Comment by crazyhottommy** [comment]
closing for now.
