### ISSUE TITLE
Error while using the CalculateSilhouette() function

### ISSUE THREAD

**Issue by aditisk** [crazyhottommy/scclusteval#6]
Hi @crazyhottommy,

I am getting an error while using the CalculateSilhouette() function, the error message is based below:

`> silhouette_scores<- CalculateSilhouette(hn, dims = 1:40)
Error in silhouette.default(cell_cluster, cell_distance) : 
  long vectors (argument 1) are not supported in .C`

Thanks in advance for your help.

**Comment by crazyhottommy** [comment]
Hi @aditisk  does the function work for the pbmc_small dataset in Seurat? or it only gives error on your seurat object?

**Comment by aditisk** [comment]
It worked on the pbmc_small dataset. The error is only on my Seurat object.

**Comment by crazyhottommy** [comment]
you have a very big matrix? I googled and found https://stackoverflow.com/questions/34165654/r-vector-size-limit-long-vectors-argument-5-are-not-supported-in-c

**Comment by aditisk** [comment]
I have a huge matrix. I found that too but I'm not sure of how feasible the code modification would be. Would modifying this function be a quick fix ?

**Comment by Paria06** [comment]
Hi @aditisk,
I'm having the same problem. did you end up finding a solution?
Thanks,
Paria

**Comment by Krithika-Bhuvan** [comment]
Has anyone found a way to resolve this ?
