### ISSUE TITLE
Run scClusterBoot on Seurat object processed through SCTransform workflow

### ISSUE THREAD

**Issue by lc822** [crazyhottommy/scclusteval#8]
Hi,

I would like to assess the stability of my scRNA-seq clusters using scClusterBoot.  Is it possible to do this on a Seurat object that has been processed using the scTransform workflow?  

I tried the following but received an error:
`scClusterBoot(sample, num.pc = 50, pc.use = 30, resolution = 0.5, k.param = 20)`

```
Error in JackStraw(object = object, num.replicate = 100, dims = num.pc) :
  JackStraw cannot be run on SCTransform-normalized data.
         Please supply a non-SCT assay.
```

I thought that by setting the `pc.use` parameter, it would stop the JackStraw step from running as suggested in `PreprocessSubsetData` but this doesn't seem to be the case.

Any thoughts?

Best wishes,
Lucy

**Comment by crazyhottommy** [comment]
Hi Lucy,
Sorry for the late reply.  Please use https://github.com/crazyhottommy/pyflow_seuratv3_parameter to do the subsampling and reclustering. `scClusterBoot` is not designed to run big dataset. The snakemake workflow will do everything in parallel.  
read this https://github.com/crazyhottommy/pyflow_seuratv3_parameter/issues/4 will help you. You then can follow the tutorial https://crazyhottommy.github.io/EvaluateSingleCellClustering/ using the scclusteval package for downstream analysis.

**Comment by lc822** [comment]
Ok great thank you.
