### ISSUE TITLE
invalid filename argument???

### ISSUE THREAD

**Issue by levinhein** [crazyhottommy/scclusteval#9]
I followed this tutorial but got an error at merging. What's happening here?

```
> gcdata <- MergeMultipleSeuratObjects(list("TCS" = TCS, "TCE" = TCE), project = "TC")
Error in dir.exists(paths = run) : invalid filename argument
```

**Comment by crazyhottommy** [comment]
MergeMultipleSeuratObjects(input_folders, do.normalize = FALSE, ...)
input_folders | A named list of folder path for each run.
-- | --
do.normalize | Whether or not normalize the data after mergeing, default is FALSE
... | Other parameters for CreatSeuratObject in the Seurat package
